server:
  port: 9000
spring:
  thymeleaf:
    cache: false
  security:
    user:
      name: yangming
      password: yangming
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      host: 192.168.3.188
      port: 27017
      database: mall-port
      username: yangming
      password: yangming
#        uri: mongodb://root:123456@192.168.3.38:27017/mall-port
  rabbitmq:
    host: 192.168.3.188
    port: 5672
    virtual-host: /yangming
    username: yangming
    password: yangming

  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: yangming #JWT负载中拿到开头